# 框架端口
port: 40004

# 环境配置
env: dev

# 测试数据库
dev-database:
  host: host
  port: 3306
  dbName: "dbName"
  userName: root
  password: "password"
  mysql-debug: true # 数据库打印
  mysql-max-idle-cons: 5 # 数据库最小连接数
  # 数据库最大连接数
  mysql-max-open-cons: 20

# 正式数据库
master-database:
  host: host
  port: 3306
  dbName: dbName
  userName: userName
  password: "password"
  mysql-debug: true # 数据库打印
  mysql-max-idle-cons: 5 # 数据库最小连接数
  # 数据库最大连接数
  mysql-max-open-cons: 20

# 测试redis
dev-redis:
  host: 127.0.0.1
  port: 6379
  password: password
  pool-size: 100

# 限流配置
rate-limit:
  fill-interval: 1 # 填充间隔时间 s为最小单位
  capacity: 100 # 容量

# jwt配置
jwt:
  sign-key: 123456 # 私钥
  bearer: false # 是否使用Bearer头

# log配置
log:
  type: file # 存储日志方式
  file:
    path: # 日志地址

# twitter配置
twitter:
  consumerKey: "consumerKey"
  consumerSecret: "consumerSecret"
  accessToken: "accessToken"
  accessTokenSecret: "accessTokenSecret"
  bearerToken: "bearerToken"

# 阿里云
aliyun:
  accessKey: accessKey
  accessSecret: accessSecret
  Endpoint: "Endpoint"
  Bucket: "Bucket"